# Generated by Django 5.0.2 on 2024-03-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='status',
            field=models.CharField(choices=[('ON', 'ON'), ('DONE', 'DONE')], default='ON', max_length=4),
        ),
    ]
